# Generated by Django 4.2.3 on 2023-07-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(blank=True)),
                ('updated_on', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
